name: Lint Shell Script

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sync-ssh-keys.sh'
      - '.github/workflows/lint.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2
        with:
          scandir: .
          severity: warning